### ISSUE TITLE
A building error - can not find com.coremedia.iso.boxes.* classes 

### ISSUE THREAD

**Issue by egslava** [RooyeKhat-Media/iGap-Android#1]
The full output from Android Studio:
https://pastebin.com/NuGsPxaS

And a screenshot:
![igap-android 2017-04-30 20-41-14](https://cloud.githubusercontent.com/assets/1143228/25564440/f38c03c6-2de5-11e7-9040-624bcc944c53.png)

**Comment by RooyeKhat** [comment]
Hi
This class need dependencies com.googlecode.mp4parser:isoparser:1.1.22 

Open your gradle.properties file in Android Studio.
Restart Android Studio for your changes to take effect.
Click Sync Project with Gradle Files to sync your project. 

Thanks

**Comment by egslava** [comment]
Thanks! It helped!
